import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import VideoProvider from "./store/video-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link
					rel="icon"
					href="/next.svg"
					sizes="any"
				/>
			</head>
			<body
				className={inter.className}
				suppressHydrationWarning={true}
			>
				<VideoProvider>{children}</VideoProvider>
			</body>
		</html>
	);
}
